- name: run bazuka from branch
  hosts: all
  gather_facts: false
  vars_files:
    - vars/bazuka.yml

  tasks:
    - name: create bazuka directory
      file:
        path: '{{ bazuka.installation_path }}/bin/'
        state: directory
    - name: create bazuka data directory
      file:
        path: '{{ bazuka.installation_path }}/data/'
        state: directory
    - name: copy bazuka to remote
      copy:
        src: ../target/release/bazuka
        dest: '{{ bazuka.installation_path }}/bin/bazuka'
        mode: a+x
    - name: copy service environment
      template:
        src: bazuka.env.j2
        dest: '{{ bazuka.installation_path }}/bazuka.env'
        mode: 644
    - name: install service
      template:
        src: bazuka.service.j2
        dest: /lib/systemd/system/bazuka.service
        mode: 644
      notify:
        - reload systemctl
    - name: start bazuka
      service:
        name: bazuka.service
        state: started
        enabled: yes
